<?php

return [
    'asset_hosts' => [
        'images.unsplash.com',
        'images.pexels.com',
        'upload.wikimedia.org',
    ],
    'asset_directory' => public_path('image/portal'),
    'assets' => [
        [
            'key' => 'hero-building',
            'url' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?fit=crop&w=1920&q=75',
            'path' => 'hero-building.jpg',
            'max_bytes' => 409600,
            'source' => 'Unsplash',
            'license' => 'Unsplash License (free use; attribution appreciated but not required): https://unsplash.com/license',
            'attribution' => null,
        ],
        [
            'key' => 'sig-logo',
            'url' => null,
            'path' => 'sig-logo.png',
            'max_bytes' => 204800,
            'source' => null,
            'license' => 'Merek dagang; gunakan berkas resmi dengan izin yang sesuai.',
            'attribution' => null,
        ],
        [
            'key' => 'semen-tonasa-logo',
            'url' => null,
            'path' => 'semen-tonasa.png',
            'max_bytes' => 204800,
            'source' => null,
            'license' => 'Merek dagang; gunakan berkas resmi dengan izin yang sesuai.',
            'attribution' => null,
        ],
    ],
    'about' => [
        'eyebrow' => 'TENTANG PLATFORM',
        'title' => 'Satu portal untuk layanan Human Capital',
        'description' => 'Portal Dept. of Human Capital & GRC menghubungkan layanan informasi dan alur kerja pengelolaan serta pengembangan talenta.',
        'steps_title' => 'Cara masuk',
        'steps' => [
            ['title' => 'Masuk ke portal', 'description' => 'Gunakan akun Anda untuk mengakses ruang kerja.'],
            ['title' => 'Pilih unit', 'description' => 'Pilih unit kerja yang sesuai.'],
            ['title' => 'Buka workspace', 'description' => 'Lanjutkan ke dashboard untuk bekerja.'],
        ],
    ],
    'features' => [
        'eyebrow' => 'FITUR',
        'title' => 'Modul Human Capital',
        'description' => 'Kenali modul yang tersedia pada platform dan layanan yang sedang dikembangkan.',
        'search_label' => 'Cari fitur',
        'search_input_label' => 'Cari modul berdasarkan nama',
        'search_placeholder' => 'Cari fitur...',
        'coming_soon_label' => 'Segera hadir',
        'empty_search' => 'Tidak ditemukan',
    ],
    'authenticated' => [
        'units_label' => 'PILIH UNIT',
        'units_title' => 'Unit kerja Anda',
        'workspace_label' => 'WORKSPACE',
        'workspace_title' => 'Mulai pekerjaan Anda',
        'empty_search' => 'Tidak ditemukan',
    ],
    'modules' => [
        [
            'slug' => 'data-pegawai',
            'name' => 'Data Pegawai',
            'icon' => 'users',
            'description' => 'Menampilkan dan mengelola informasi administrasi pegawai.',
            'detail' => 'Modul ini menyediakan alur untuk melihat, memperbarui, mengimpor, dan mengekspor data pegawai.',
        ],
        [
            'slug' => 'wla',
            'name' => 'WLA (Workload Analysis)',
            'icon' => 'chart',
            'description' => 'Mendukung pencatatan aktivitas dan penilaian analisis beban kerja.',
            'detail' => 'Workspace WLA mengelola asesmen, aktivitas, jadwal kerja, dan kalender kerja.',
        ],
        [
            'slug' => 'fit-proper',
            'name' => 'Fit & Proper',
            'icon' => 'clipboard',
            'description' => 'Informasi mengenai proses penilaian kecocokan dan kelayakan kandidat.',
            'detail' => 'Modul Fit & Proper masih dalam tahap pengembangan.',
            'coming_soon' => true,
        ],
        [
            'slug' => 'mutasi',
            'name' => 'Mutasi',
            'icon' => 'arrows',
            'description' => 'Mencatat dan mengelola usulan mutasi pegawai.',
            'detail' => 'Alur mutasi mendukung pencatatan, peninjauan, dan persetujuan usulan.',
        ],
        [
            'slug' => 'promosi',
            'name' => 'Promosi',
            'icon' => 'promotion',
            'description' => 'Mencatat dan mengelola usulan promosi pegawai.',
            'detail' => 'Alur promosi mendukung pencatatan, peninjauan, dan persetujuan usulan.',
        ],
        [
            'slug' => 'demosi',
            'name' => 'Demosi',
            'icon' => 'demosi',
            'description' => 'Mencatat dan mengelola usulan demosi pegawai.',
            'detail' => 'Alur demosi mendukung pencatatan, peninjauan, dan persetujuan usulan.',
        ],
        [
            'slug' => 'formasi',
            'name' => 'Formasi',
            'icon' => 'formasi',
            'description' => 'Informasi mengenai perencanaan formasi jabatan.',
            'detail' => 'Modul Formasi masih dalam tahap pengembangan.',
            'coming_soon' => true,
        ],
        [
            'slug' => 'definitif',
            'name' => 'Definitif',
            'icon' => 'definitif',
            'description' => 'Informasi mengenai pengelolaan penetapan pegawai definitif.',
            'detail' => 'Modul Definitif masih dalam tahap pengembangan.',
            'coming_soon' => true,
        ],
        [
            'slug' => 'laporan',
            'name' => 'Laporan',
            'icon' => 'document',
            'description' => 'Informasi mengenai ringkasan dan keluaran pelaporan Human Capital.',
            'detail' => 'Modul Laporan masih dalam tahap pengembangan.',
            'coming_soon' => true,
        ],
    ],
    'units' => [
        [
            'slug' => 'hc-planning-development',
            'name' => 'HC Planning & Development',
            'workspace_heading' => 'UNIT HC PLANNING & DEVELOPMENT',
            'status' => 'Active',
            'workspaces' => [
                [
                    'slug' => 'hc-od-career-management',
                    'name' => 'HC OD & Career Management',
                    'icon' => 'org-chart',
                    'tone' => 'blue',
                ],
                [
                    'slug' => 'performance-talent-management',
                    'name' => 'Performance & Talent Management',
                    'icon' => 'target',
                    'tone' => 'green',
                ],
            ],
        ],
    ],
    'footer' => [
        'organization' => 'Dept. of Human Capital & GRC',
        'description' => 'Portal layanan informasi, alur kerja, dan pengembangan talenta Dept. of Human Capital & GRC.',
        'navigation_title' => 'Navigasi',
        'unit_title' => 'Unit aktif',
        'active_unit_name' => 'HC Planning & Development',
        'guest_unit_title' => 'Layanan Human Capital',
        'guest_unit_description' => 'Informasi umum mengenai modul dan layanan Dept. of Human Capital & GRC.',
        'photo_credit_label' => 'Foto hero',
        'copyright' => 'SIG – Dept. of Human Capital & GRC. Hak cipta dilindungi.',
        'photo_credit_label' => 'Foto hero',
        'guest_links' => [
            ['label' => 'Fitur', 'anchor' => 'fitur'],
            ['label' => 'Masuk ke Portal', 'route' => 'login'],
        ],
        'authenticated_links' => [
            ['label' => 'Pilih Unit', 'anchor' => 'pilih-unit'],
            ['label' => 'Workspace', 'anchor' => 'workspace'],
        ],
    ],
];
