<form method="POST" action="{{ $action }}" x-data="{ departmentId: @js(old('department_id', $position?->unit?->department_id ?? '')), unitId: @js((string) old('unit_id', $position?->unit_id ?? '')), units: @js($units->map(fn ($unit) => ['id' => $unit->id, 'department_id' => $unit->department_id, 'label' => $unit->code.' · '.$unit->name.' / '.$unit->department->name])) }" class="mt-6 space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
    @csrf
    @if ($method !== 'POST')@method($method)@endif
    <div><label for="department_id" class="text-sm font-semibold text-slate-700">Department</label><select id="department_id" x-model="departmentId" x-on:change="unitId = ''" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm focus:border-amber-400 focus:ring-amber-400"><option value="">Pilih Department</option>@foreach ($departments as $department)<option value="{{ $department->id }}">{{ $department->code }} · {{ $department->name }}{{ $department->active ? '' : ' (Nonaktif)' }}</option>@endforeach</select></div>
    <div><label for="unit_id" class="text-sm font-semibold text-slate-700">Unit</label><select id="unit_id" name="unit_id" x-model="unitId" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm focus:border-amber-400 focus:ring-amber-400"><option value="">Pilih Unit</option><template x-for="unit in units.filter(item => !departmentId || String(item.department_id) === String(departmentId))" :key="unit.id"><option :value="String(unit.id)" x-text="unit.label"></option></template></select>@error('unit_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="code" class="text-sm font-semibold text-slate-700">Kode</label><input id="code" name="code" value="{{ old('code', $position?->code) }}" required maxlength="50" class="mt-1 block w-full rounded-lg border-slate-300 text-sm focus:border-amber-400 focus:ring-amber-400">@error('code')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="name" class="text-sm font-semibold text-slate-700">Nama</label><input id="name" name="name" value="{{ old('name', $position?->name) }}" required maxlength="255" class="mt-1 block w-full rounded-lg border-slate-300 text-sm focus:border-amber-400 focus:ring-amber-400">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><input type="hidden" name="active" value="0"><label class="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="active" value="1" @checked((bool) old('active', $position?->active ?? true)) class="rounded border-slate-300 text-amber-500 focus:ring-amber-400"> Aktif</label>@error('active')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="flex justify-end gap-3 border-t border-slate-100 pt-4"><a href="{{ route('organization.positions.index') }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Batal</a><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Simpan</button></div>
</form>