@extends('layouts.app')

@section('page-title', 'Fit & Proper')

@section('content')
    <div class="mb-8"><p class="text-sm text-slate-500">Kelola proses penilaian kompetensi dan kelayakan kandidat.</p><h2 class="mt-1 font-display text-3xl font-bold tracking-tight text-slate-950">Daftar Fit & Proper</h2></div>
    <div class="grid gap-5 md:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Menunggu penilaian</p><p class="mt-2 font-display text-3xl font-bold text-slate-950">42</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Sedang diproses</p><p class="mt-2 font-display text-3xl font-bold text-slate-950">68</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Selesai</p><p class="mt-2 font-display text-3xl font-bold text-emerald-600">18</p></div></div>
+    <div class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-display text-lg font-bold text-slate-950">Data kandidat terbaru</h3><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><tr><th class="pb-3">Nama kandidat</th><th class="pb-3">Jabatan</th><th class="pb-3">Status</th><th class="pb-3">Tanggal</th></tr></thead><tbody class="divide-y divide-slate-100"><tr><td class="py-4 font-semibold text-slate-700">Andi Pratama</td><td class="py-4 text-slate-500">Manager Operasional</td><td class="py-4"><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Menunggu</span></td><td class="py-4 text-slate-500">24 Sep 2026</td></tr><tr><td class="py-4 font-semibold text-slate-700">Sari Wulandari</td><td class="py-4 text-slate-500">Kepala Divisi</td><td class="py-4"><span class="rounded-full bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-700">Diproses</span></td><td class="py-4 text-slate-500">23 Sep 2026</td></tr></tbody></table></div></div>
@endsection
