@extends('layouts.app')

@section('page-title', 'Laporan')

@section('content')
    <div class="mb-8"><p class="text-sm text-slate-500">Akses ringkasan dan laporan operasional human capital.</p><h2 class="mt-1 font-display text-3xl font-bold tracking-tight text-slate-950">Pusat Laporan</h2></div>
    <div class="grid gap-5 md:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Laporan tersedia</p><p class="mt-2 font-display text-3xl font-bold text-slate-950">18</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Dibuat bulan ini</p><p class="mt-2 font-display text-3xl font-bold text-slate-950">7</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Terakhir diperbarui</p><p class="mt-2 font-display text-3xl font-bold text-emerald-600">Hari ini</p></div></div>
+    <div class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-display text-lg font-bold text-slate-950">Laporan terbaru</h3><div class="mt-5 divide-y divide-slate-100"><a href="#" class="flex items-center justify-between py-4"><div><p class="font-semibold text-slate-700">Rekapitulasi Mutasi Pegawai</p><p class="mt-1 text-xs text-slate-400">Diperbarui 24 September 2026</p></div><span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">PDF</span></a><a href="#" class="flex items-center justify-between py-4"><div><p class="font-semibold text-slate-700">Laporan Promosi Kuartal III</p><p class="mt-1 text-xs text-slate-400">Diperbarui 20 September 2026</p></div><span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">PDF</span></a><a href="#" class="flex items-center justify-between py-4"><div><p class="font-semibold text-slate-700">Hasil Fit & Proper</p><p class="mt-1 text-xs text-slate-400">Diperbarui 18 September 2026</p></div><span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">PDF</span></a></div></div>
@endsection
