@extends('layouts.app')

@section('page-title', 'WLA')

@section('content')
    <div class="mb-8"><p class="text-sm text-slate-500">Workload Analysis untuk memantau beban kerja setiap unit.</p><h2 class="mt-1 font-display text-3xl font-bold tracking-tight text-slate-950">Workload Analysis</h2></div>
    <div class="grid gap-5 md:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Unit dianalisis</p><p class="mt-2 font-display text-3xl font-bold text-slate-950">18</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Beban kerja ideal</p><p class="mt-2 font-display text-3xl font-bold text-emerald-600">72%</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Perlu evaluasi</p><p class="mt-2 font-display text-3xl font-bold text-amber-600">5</p></div></div>
    <div class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-display text-lg font-bold text-slate-950">Ringkasan beban kerja</h3><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><tr><th class="pb-3">Unit kerja</th><th class="pb-3">Kapasitas</th><th class="pb-3">Beban saat ini</th><th class="pb-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100"><tr><td class="py-4 font-semibold text-slate-700">Operasional</td><td class="py-4 text-slate-500">100%</td><td class="py-4 text-slate-500">86%</td><td class="py-4"><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Seimbang</span></td></tr><tr><td class="py-4 font-semibold text-slate-700">Layanan Nasabah</td><td class="py-4 text-slate-500">100%</td><td class="py-4 text-slate-500">118%</td><td class="py-4"><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Overload</span></td></tr></tbody></table></div></div>
@endsection
